### PR TITLE
Build improvements

### PR DESCRIPTION
**Pull request by Trass3r**

### CODE REVIEW

**Comment by edmcman** [comment]
There's a lot of good stuff here.  We're discussing the changes.  Here are some of my notes/open questions for us to discuss.  @Trass3r the only question I have for you is regarding the shallow clone commit; I don't understand the motivation behind it.

- We need to document `--delete-method`
- We need to fix boost path, but I'd rather set to `/usr` to be more consistent with the general pattern of explicitly setting the options
- Installing deps/building prereqs utilizes the cache better, but does it also increase the size of the produced Docker image?
- Do we want to use ninja?
- @Trass3r What is the purpose of the "use shallow clones" commit? Z3 doesn't have any submodules, and I don't think we want to clone ROSE recursively.
- Parallel tests: we just merged a fix for this
- fix rose cmake flags: these all seem good

**Comment by Trass3r** [comment]
* More docker steps shouldn't increase the final image, only the space used on the build machine.
  I even [experimented](https://github.com/Trass3r/pharos/commit/3cddc1b71844b2d6050e598d9f2b7b6d108e3bef) with multi-stage builds to reduce the runtime image size but unfortunately it still pulls in a lot of stuff like gcc due to package dependencies.
* I always use Ninja as it's usually faster than make, at least for incremental builds.
* Shallow clones don't pull all the history, nothing to do with submodules. Maybe it reduces the clone time a bit.

**Comment by sei-eschwartz** [comment]
We merged a lot of these changes in just now.  We'll continue working on the other ones.

**Comment by sei-eschwartz** [comment]
All of these are effectively merged now except for splitting the prerequisites into a separate build step.  I confirmed that doing so does not increase the size of the Docker image, and will merge that soon.

**Comment by Trass3r** [comment]
All but the gcc-8 change it seems, deliberately?

**Comment by edmcman** [comment]
I think we want to stick with Ubuntu LTS for now.  Is there a reason you wanted gcc 8?

**Comment by Trass3r** [comment]
Just better codegen. Every bit may help to speed things up given how CPU bound the analysis is :)

**Comment by sei-eschwartz** [comment]
Ok, all is merged except the new version of Ubuntu.  We'll discuss that internally.  Maybe we'll produce multiple Docker images for different versions of Ubuntu.

**Pull request closed without merging**
