### PR TITLE
optimize Dockerfile

### PR DESCRIPTION
**Pull request by LyleMi**
Hello, I made the following changes to the Dockerfile to optimize it.

At first, I change `FROM ubuntu:latest` to `FROM ubuntu:16.04`, to prevent compatibility issues due to ubuntu update.

Then, I put `ADD . /root/pharos`  after `apt-get`. This is because if you put the source code in front, you must rebuild the apt layer each time you update the code.

At last, I put `apt-get update` and `apt-get install` to same layer, this will reduce the use of the disk.

I hope this RP does not bother you.

### CODE REVIEW

**Comment by sei-eschwartz** [comment]
I'm fine with changes 2-3, but can you undo the change to the base image?

**Comment by LyleMi** [comment]
Ok, I have modified it back.

**Comment by sei-eschwartz** [comment]
Thanks for the contribution!

**Comment by LyleMi** [comment]
You're welcome :P

**Pull request merged**
